#!/usr/bin/perl -sw

my $showFilename = (@ARGV < 2) ? 0 : 1;
while (<>) {
	unless (/^[[:print:][:cntrl:]]*$/a) {
		if ($showFilename) {
			print "$ARGV:$.: $_";
		} else {
			print "$.: $_";
		}
	}
	close ARGV if eof;
}
